use std::str::FromStr;
use num::integer::{div_floor,mod_floor};

grammar;

pub Expr: i32 = {
    <l:Expr> "+" <r:Factor> => l + r,
    <l:Expr> "-" <r:Factor> => l - r,
    Factor,
};

Factor: i32 = {
    <l:Factor> "*" <r:Term> => l * r,
    <l:Factor> "/" <r:Term> => div_floor(l, r),
    <l:Factor> "%" <r:Term> => mod_floor(l, r),
    Term,
};

Term: i32 = {
    Num,
    "(" <Expr> ")",
    "-" <Term> => -<>,
};

Num: i32 = {
    r"[0-9]+" => i32::from_str(<>).unwrap(),
};