[package]
name = "knuth_morris_pratt"
version = "0.1.0"
authors = ["Jakub"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
path="src/knuth_morris_pratt.rs"
