[package]
name = "lab1"
version = "0.1.0"
authors = ["Jakub"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
automaton = { path = "./automaton" }
knuth_morris_pratt = { path = "./knuth_morris_pratt" }
